import { Country } from '../review/models/country';
import { City } from '../review/models/city';
import { Mission, MissionDetails } from '../review/models/mission';
import {
  Message,
  MessageDetails,
  MessageStatus,
} from '../review/models/message';

interface IData {
  countries: Country[];
  cities: City[];
  missions: Mission[];
  messages: Message[];
  messageDetails: MessageDetails[];
  missionDetails: MissionDetails[];
}

export const database: IData = {
  countries: [
    { id: 1, name: 'Denmark' },
    { id: 2, name: 'Sweden' },
    { id: 3, name: 'Germany' },
  ],
  cities: [
    { id: 1, countryId: 1, name: 'Copenhagen' },
    { id: 2, countryId: 1, name: 'Aarhus' },
    { id: 3, countryId: 1, name: 'Odense' },
    { id: 4, countryId: 1, name: 'Esbjerg' },
    { id: 5, countryId: 2, name: 'Arvika' },
    { id: 6, countryId: 2, name: 'Borgholm' },
    { id: 7, countryId: 2, name: 'Falun' },
    { id: 8, countryId: 2, name: 'Kalmar' },
    { id: 9, countryId: 2, name: 'Lund' },
    { id: 10, countryId: 3, name: 'Abensberg' },
    { id: 11, countryId: 3, name: 'Ellrich' },
    { id: 12, countryId: 3, name: 'Immenhausen' },
    { id: 13, countryId: 3, name: 'Langelsheim' },
    { id: 14, countryId: 3, name: 'Plettenberg' },
  ],
  missions: [
    { id: 0, cityId: 11, title: 'Numb Biscuit' },
    { id: 1, cityId: 12, title: 'Muted Gambit' },
    { id: 2, cityId: 1, title: 'Frozen Eyes' },
    { id: 3, cityId: 9, title: 'Arctic Lizard' },
    { id: 4, cityId: 5, title: 'Enchanted Tuner' },
    { id: 5, cityId: 9, title: 'False Serpent' },
    { id: 6, cityId: 2, title: 'Buzzing Devil' },
    { id: 7, cityId: 4, title: 'Humming Tuner' },
    { id: 8, cityId: 11, title: 'Rare Foxtail' },
    { id: 9, cityId: 2, title: 'Silent Lurker' },
    { id: 10, cityId: 2, title: 'Busy Demon' },
    { id: 11, cityId: 11, title: 'Calm Balboa' },
    { id: 12, cityId: 12, title: 'Old Robin' },
    { id: 13, cityId: 8, title: 'Dangerous Whisper' },
    { id: 14, cityId: 11, title: 'Lucky Clown' },
    { id: 15, cityId: 7, title: 'Cool Prince' },
    { id: 16, cityId: 5, title: 'Twin Enigma' },
    { id: 17, cityId: 6, title: 'Jasper Volunteer' },
    { id: 18, cityId: 14, title: 'Heavy Knight' },
    { id: 19, cityId: 5, title: 'Cheap Clown' },
  ],
  messages: [
    {
      cityId: 2,
      id: 0,
      title: 'Peter found road kill an excellent way to save money on dinner.',
      status: MessageStatus.New,
    },
    {
      cityId: 7,
      id: 1,
      title: 'In the end, he realized he could see sound and hear words.',
      status: MessageStatus.New,
    },
    {
      cityId: 13,
      id: 2,
      title:
        "I've traveled all around Africa and still haven't found the gnu who stole my scarf.",
      status: MessageStatus.New,
    },
    {
      cityId: 10,
      id: 3,
      title: 'More RVs were seen in the storage lot than at the campground.',
      status: MessageStatus.New,
    },
    {
      cityId: 13,
      id: 4,
      title: 'So long and thanks for the fish.',
      status: MessageStatus.New,
    },
    {
      cityId: 11,
      id: 5,
      title: 'He had decided to accept his fate of accepting his fate.',
      status: MessageStatus.New,
    },
    {
      cityId: 12,
      id: 6,
      title: 'Jenny made the announcement that her baby was an alien.',
      status: MessageStatus.New,
    },
    {
      cityId: 1,
      id: 7,
      title:
        "On a scale from one to ten, what's your favorite flavor of random grammar?",
      status: MessageStatus.New,
    },
    {
      cityId: 6,
      id: 8,
      title:
        'The white water rafting trip was suddenly halted by the unexpected brick wall.',
      status: MessageStatus.New,
    },
    {
      cityId: 9,
      id: 9,
      title: 'It was obvious she was hot, sweaty, and tired.',
      status: MessageStatus.New,
    },
    {
      cityId: 1,
      id: 10,
      title:
        'People who insist on picking their teeth with their elbows are so annoying!',
      status: MessageStatus.New,
    },
    {
      cityId: 14,
      id: 11,
      title: 'Getting up at dawn is for the birds.',
      status: MessageStatus.New,
    },
    {
      cityId: 3,
      id: 12,
      title: 'He swore he just saw his sushi move.',
      status: MessageStatus.New,
    },
    {
      cityId: 6,
      id: 13,
      title: 'He found the chocolate covered roaches quite tasty.',
      status: MessageStatus.New,
    },
    {
      cityId: 9,
      id: 14,
      title:
        'He wore the surgical mask in public not to keep from catching a virus, but to keep people away from him.',
      status: MessageStatus.New,
    },
    {
      cityId: 13,
      id: 15,
      title: 'Not all people who wander are lost.',
      status: MessageStatus.New,
    },
    {
      cityId: 8,
      id: 16,
      title:
        "It's important to remember to be aware of rampaging grizzly bears.",
      status: MessageStatus.New,
    },
    {
      cityId: 6,
      id: 17,
      title: "I trust everything that's written in purple ink.",
      status: MessageStatus.New,
    },
    {
      cityId: 14,
      id: 18,
      title:
        "It's much more difficult to play tennis with a bowling ball than it is to bowl with a tennis ball.",
      status: MessageStatus.New,
    },
    {
      cityId: 7,
      id: 19,
      title:
        "It isn't difficult to do a handstand if you just stand on your hands.",
      status: MessageStatus.New,
    },
    {
      cityId: 11,
      id: 20,
      title:
        'When he encountered maize for the first time, he thought it incredibly corny.',
      status: MessageStatus.New,
    },
    {
      cityId: 7,
      id: 21,
      title:
        "It must be easy to commit crimes as a snake because you don't have to worry about leaving fingerprints.",
      status: MessageStatus.New,
    },
    {
      cityId: 11,
      id: 22,
      title:
        'I purchased a baby clown from the Russian terrorist black market.',
      status: MessageStatus.New,
    },
    {
      cityId: 4,
      id: 23,
      title: "The elephant didn't want to talk about the person in the room.",
      status: MessageStatus.New,
    },
    {
      cityId: 5,
      id: 24,
      title:
        'In hopes of finding out the truth, he entered the one-room library.',
      status: MessageStatus.New,
    },
    {
      cityId: 3,
      id: 25,
      title:
        'He set out for a short walk, but now all he could see were mangroves and water were for miles.',
      status: MessageStatus.New,
    },
    {
      cityId: 13,
      id: 26,
      title:
        'It was at that moment that he learned there are certain parts of the body that you should never Nair.',
      status: MessageStatus.New,
    },
    {
      cityId: 8,
      id: 27,
      title: 'There was coal in his stocking and he was thrilled.',
      status: MessageStatus.New,
    },
    {
      cityId: 1,
      id: 28,
      title:
        'She did not cheat on the test, for it was not the right thing to do.',
      status: MessageStatus.New,
    },
    {
      cityId: 14,
      id: 29,
      title: "A dead duck doesn't fly backward.",
      status: MessageStatus.New,
    },
    {
      cityId: 4,
      id: 30,
      title:
        'Despite what your teacher may have told you, there is a wrong way to wield a lasso.',
      status: MessageStatus.New,
    },
    {
      cityId: 5,
      id: 31,
      title: 'Please wait outside of the house.',
      status: MessageStatus.New,
    },
    {
      cityId: 7,
      id: 32,
      title:
        'The child’s favorite Christmas gift was the large box her father’s lawnmower came in.',
      status: MessageStatus.New,
    },
    {
      cityId: 12,
      id: 33,
      title: 'Little Red Riding Hood decided to wear orange today.',
      status: MessageStatus.New,
    },
    {
      cityId: 4,
      id: 34,
      title:
        'She always had an interesting perspective on why the world must be flat.',
      status: MessageStatus.New,
    },
    {
      cityId: 6,
      id: 35,
      title:
        'Car safety systems have come a long way, but he was out to prove they could be outsmarted.',
      status: MessageStatus.New,
    },
    {
      cityId: 10,
      id: 36,
      title: 'He decided to live his life by the big beats manifesto.',
      status: MessageStatus.New,
    },
    {
      cityId: 3,
      id: 37,
      title: "I'd rather be a bird than a fish.",
      status: MessageStatus.New,
    },
    {
      cityId: 4,
      id: 38,
      title: "He was the only member of the club who didn't like plum pudding.",
      status: MessageStatus.New,
    },
    {
      cityId: 8,
      id: 39,
      title:
        'He was the type of guy who liked Christmas lights on his house in the middle of July.',
      status: MessageStatus.New,
    },
    {
      cityId: 12,
      id: 40,
      title:
        'Kevin embraced his ability to be at the wrong place at the wrong time.',
      status: MessageStatus.New,
    },
    {
      cityId: 1,
      id: 41,
      title: 'He colored deep space a soft yellow.',
      status: MessageStatus.New,
    },
    {
      cityId: 8,
      id: 42,
      title:
        'He would only survive if he kept the fire going and he could hear thunder in the distance.',
      status: MessageStatus.New,
    },
    {
      cityId: 10,
      id: 43,
      title:
        'Patricia loves the sound of nails strongly pressed against the chalkboard.',
      status: MessageStatus.New,
    },
    {
      cityId: 5,
      id: 44,
      title:
        'She wanted to be rescued, but only if it was Tuesday and raining.',
      status: MessageStatus.New,
    },
    {
      cityId: 1,
      id: 45,
      title:
        'He went back to the video to see what had been recorded and was shocked at what he saw.',
      status: MessageStatus.New,
    },
    {
      cityId: 1,
      id: 46,
      title: 'Today I dressed my unicorn in preparation for the race.',
      status: MessageStatus.New,
    },
    {
      cityId: 7,
      id: 47,
      title:
        'The teenage boy was accused of breaking his arm simply to get out of the test.',
      status: MessageStatus.New,
    },
    {
      cityId: 10,
      id: 48,
      title: 'The bug was having an excellent day until he hit the windshield.',
      status: MessageStatus.New,
    },
    {
      cityId: 8,
      id: 49,
      title:
        'At that moment I was the most fearsome weasel in the entire swamp.',
      status: MessageStatus.New,
    },
  ],
  messageDetails: [
    {
      id: 0,
      messageId: 0,
      code: 'OHFLFS713',
      delivered: '2022-01-10T00:00:00.000Z',
      reliability: 68,
    },
    {
      id: 1,
      messageId: 1,
      code: 'SQTHFF163',
      delivered: '2022-01-12T00:00:00.000Z',
      reliability: 60,
    },
    {
      id: 2,
      messageId: 2,
      code: 'AGMGPP145',
      delivered: '2022-01-14T00:00:00.000Z',
      reliability: 73,
    },
    {
      id: 3,
      messageId: 3,
      code: 'IGTFAP664',
      delivered: '2022-01-16T00:00:00.000Z',
      reliability: 75,
    },
    {
      id: 4,
      messageId: 4,
      code: 'HOQTOR314',
      delivered: '2022-01-18T00:00:00.000Z',
      reliability: 58,
    },
    {
      id: 5,
      messageId: 5,
      code: 'KAFCFG116',
      delivered: '2022-01-20T00:00:00.000Z',
      reliability: 13,
    },
    {
      id: 6,
      messageId: 6,
      code: 'FGEDPF684',
      delivered: '2022-01-22T00:00:00.000Z',
      reliability: 47,
    },
    {
      id: 7,
      messageId: 7,
      code: 'IFPCGQ148',
      delivered: '2022-01-24T00:00:00.000Z',
      reliability: 60,
    },
    {
      id: 8,
      messageId: 8,
      code: 'NLHGMD722',
      delivered: '2022-01-26T00:00:00.000Z',
      reliability: 19,
    },
    {
      id: 9,
      messageId: 9,
      code: 'BLIPRJ490',
      delivered: '2022-01-28T00:00:00.000Z',
      reliability: 18,
    },
    {
      id: 10,
      messageId: 10,
      code: 'LOKSDI348',
      delivered: '2022-01-30T00:00:00.000Z',
      reliability: 87,
    },
    {
      id: 11,
      messageId: 11,
      code: 'JTIBAD983',
      delivered: '2022-02-01T00:00:00.000Z',
      reliability: 89,
    },
    {
      id: 12,
      messageId: 12,
      code: 'STGESH912',
      delivered: '2022-02-03T00:00:00.000Z',
      reliability: 28,
    },
    {
      id: 13,
      messageId: 13,
      code: 'PPNTRD616',
      delivered: '2022-02-05T00:00:00.000Z',
      reliability: 94,
    },
    {
      id: 14,
      messageId: 14,
      code: 'BAHPEA648',
      delivered: '2022-02-07T00:00:00.000Z',
      reliability: 92,
    },
    {
      id: 15,
      messageId: 15,
      code: 'DNSFAD942',
      delivered: '2022-02-09T00:00:00.000Z',
      reliability: 38,
    },
    {
      id: 16,
      messageId: 16,
      code: 'QAQHAS844',
      delivered: '2022-02-11T00:00:00.000Z',
      reliability: 99,
    },
    {
      id: 17,
      messageId: 17,
      code: 'GHMECH510',
      delivered: '2022-02-13T00:00:00.000Z',
      reliability: 11,
    },
    {
      id: 18,
      messageId: 18,
      code: 'SRHOIR846',
      delivered: '2022-02-15T00:00:00.000Z',
      reliability: 58,
    },
    {
      id: 19,
      messageId: 19,
      code: 'DCPOBS317',
      delivered: '2022-02-17T00:00:00.000Z',
      reliability: 90,
    },
    {
      id: 20,
      messageId: 20,
      code: 'EPBEMP225',
      delivered: '2022-02-19T00:00:00.000Z',
      reliability: 45,
    },
    {
      id: 21,
      messageId: 21,
      code: 'TPJRTI181',
      delivered: '2022-02-21T00:00:00.000Z',
      reliability: 28,
    },
    {
      id: 22,
      messageId: 22,
      code: 'HDEEON634',
      delivered: '2022-02-23T00:00:00.000Z',
      reliability: 19,
    },
    {
      id: 23,
      messageId: 23,
      code: 'FATEKI858',
      delivered: '2022-02-25T00:00:00.000Z',
      reliability: 19,
    },
    {
      id: 24,
      messageId: 24,
      code: 'DSGJCK134',
      delivered: '2022-02-27T00:00:00.000Z',
      reliability: 54,
    },
    {
      id: 25,
      messageId: 25,
      code: 'ITFHSH493',
      delivered: '2022-03-01T00:00:00.000Z',
      reliability: 18,
    },
    {
      id: 26,
      messageId: 26,
      code: 'DNDJBT301',
      delivered: '2022-03-03T00:00:00.000Z',
      reliability: 22,
    },
    {
      id: 27,
      messageId: 27,
      code: 'DQCFMI187',
      delivered: '2022-03-05T00:00:00.000Z',
      reliability: 91,
    },
    {
      id: 28,
      messageId: 28,
      code: 'FIJBPI269',
      delivered: '2022-03-07T00:00:00.000Z',
      reliability: 85,
    },
    {
      id: 29,
      messageId: 29,
      code: 'JHIGQF972',
      delivered: '2022-03-09T00:00:00.000Z',
      reliability: 22,
    },
    {
      id: 30,
      messageId: 30,
      code: 'COQERC243',
      delivered: '2022-03-11T00:00:00.000Z',
      reliability: 57,
    },
    {
      id: 31,
      messageId: 31,
      code: 'ECEDMQ542',
      delivered: '2022-03-13T00:00:00.000Z',
      reliability: 57,
    },
    {
      id: 32,
      messageId: 32,
      code: 'NIOFHR519',
      delivered: '2022-03-15T00:00:00.000Z',
      reliability: 68,
    },
    {
      id: 33,
      messageId: 33,
      code: 'TKTLHQ482',
      delivered: '2022-03-17T00:00:00.000Z',
      reliability: 92,
    },
    {
      id: 34,
      messageId: 34,
      code: 'LKOHAQ125',
      delivered: '2022-03-19T00:00:00.000Z',
      reliability: 26,
    },
    {
      id: 35,
      messageId: 35,
      code: 'BQPNTD944',
      delivered: '2022-03-21T00:00:00.000Z',
      reliability: 13,
    },
    {
      id: 36,
      messageId: 36,
      code: 'ITQKPH872',
      delivered: '2022-03-23T00:00:00.000Z',
      reliability: 13,
    },
    {
      id: 37,
      messageId: 37,
      code: 'JLGDLH713',
      delivered: '2022-03-25T00:00:00.000Z',
      reliability: 40,
    },
    {
      id: 38,
      messageId: 38,
      code: 'BDBIHC651',
      delivered: '2022-03-27T00:00:00.000Z',
      reliability: 83,
    },
    {
      id: 39,
      messageId: 39,
      code: 'FQIOBG719',
      delivered: '2022-03-29T00:00:00.000Z',
      reliability: 92,
    },
    {
      id: 40,
      messageId: 40,
      code: 'TJCGPH855',
      delivered: '2022-03-31T00:00:00.000Z',
      reliability: 29,
    },
    {
      id: 41,
      messageId: 41,
      code: 'JOALMJ709',
      delivered: '2022-04-02T00:00:00.000Z',
      reliability: 74,
    },
    {
      id: 42,
      messageId: 42,
      code: 'HCPTMT112',
      delivered: '2022-04-04T00:00:00.000Z',
      reliability: 41,
    },
    {
      id: 43,
      messageId: 43,
      code: 'TBTEOM737',
      delivered: '2022-04-06T00:00:00.000Z',
      reliability: 20,
    },
    {
      id: 44,
      messageId: 44,
      code: 'ADJSMB179',
      delivered: '2022-04-08T00:00:00.000Z',
      reliability: 79,
    },
    {
      id: 45,
      messageId: 45,
      code: 'LPQLGQ323',
      delivered: '2022-04-10T00:00:00.000Z',
      reliability: 87,
    },
    {
      id: 46,
      messageId: 46,
      code: 'IQFEDR594',
      delivered: '2022-04-12T00:00:00.000Z',
      reliability: 43,
    },
    {
      id: 47,
      messageId: 47,
      code: 'GAKSEJ438',
      delivered: '2022-04-14T00:00:00.000Z',
      reliability: 34,
    },
    {
      id: 48,
      messageId: 48,
      code: 'DCKDSL276',
      delivered: '2022-04-16T00:00:00.000Z',
      reliability: 77,
    },
    {
      id: 49,
      messageId: 49,
      code: 'HBEPCT614',
      delivered: '2022-04-18T00:00:00.000Z',
      reliability: 76,
    },
  ],
  missionDetails: [
    {
      id: 0,
      missionId: 0,
      agent: 'Silent',
      dangerRate: 20,
      potential: 16,
      expectedCompletionDate: '2022-03-02T23:00:00.000Z',
    },
    {
      id: 1,
      missionId: 1,
      agent: 'Mercury',
      dangerRate: 69,
      potential: 82,
      expectedCompletionDate: '2022-10-03T22:00:00.000Z',
    },
    {
      id: 2,
      missionId: 2,
      agent: 'Neon',
      dangerRate: 37,
      potential: 34,
      expectedCompletionDate: '2022-10-08T22:00:00.000Z',
    },
    {
      id: 3,
      missionId: 3,
      agent: 'Mega',
      dangerRate: 0,
      potential: 43,
      expectedCompletionDate: '2022-06-30T22:00:00.000Z',
    },
    {
      id: 4,
      missionId: 4,
      agent: 'King',
      dangerRate: 3,
      potential: 47,
      expectedCompletionDate: '2022-01-01T23:00:00.000Z',
    },
    {
      id: 5,
      missionId: 5,
      agent: 'Neon',
      dangerRate: 83,
      potential: 35,
      expectedCompletionDate: '2022-01-03T23:00:00.000Z',
    },
    {
      id: 6,
      missionId: 6,
      agent: 'Glowing',
      dangerRate: 3,
      potential: 99,
      expectedCompletionDate: '2022-01-30T23:00:00.000Z',
    },
    {
      id: 7,
      missionId: 7,
      agent: 'Dizzy',
      dangerRate: 86,
      potential: 28,
      expectedCompletionDate: '2022-05-04T22:00:00.000Z',
    },
    {
      id: 8,
      missionId: 8,
      agent: 'Fox',
      dangerRate: 58,
      potential: 12,
      expectedCompletionDate: '2022-07-31T22:00:00.000Z',
    },
    {
      id: 9,
      missionId: 9,
      agent: 'Mega',
      dangerRate: 75,
      potential: 75,
      expectedCompletionDate: '2022-01-05T23:00:00.000Z',
    },
    {
      id: 10,
      missionId: 10,
      agent: 'Neon',
      dangerRate: 5,
      potential: 34,
      expectedCompletionDate: '2022-02-01T23:00:00.000Z',
    },
    {
      id: 11,
      missionId: 11,
      agent: 'Hungry',
      dangerRate: 45,
      potential: 1,
      expectedCompletionDate: '2022-07-01T22:00:00.000Z',
    },
    {
      id: 12,
      missionId: 12,
      agent: 'Dancer',
      dangerRate: 59,
      potential: 9,
      expectedCompletionDate: '2022-08-06T22:00:00.000Z',
    },
    {
      id: 13,
      missionId: 13,
      agent: 'Glowing',
      dangerRate: 70,
      potential: 52,
      expectedCompletionDate: '2022-06-29T22:00:00.000Z',
    },
    {
      id: 14,
      missionId: 14,
      agent: 'King',
      dangerRate: 72,
      potential: 0,
      expectedCompletionDate: '2022-09-07T22:00:00.000Z',
    },
    {
      id: 15,
      missionId: 15,
      agent: 'Silent',
      dangerRate: 18,
      potential: 3,
      expectedCompletionDate: '2022-09-30T22:00:00.000Z',
    },
    {
      id: 16,
      missionId: 16,
      agent: 'Spotty',
      dangerRate: 26,
      potential: 93,
      expectedCompletionDate: '2022-09-08T22:00:00.000Z',
    },
    {
      id: 17,
      missionId: 17,
      agent: 'Visible',
      dangerRate: 76,
      potential: 63,
      expectedCompletionDate: '2021-12-31T23:00:00.000Z',
    },
    {
      id: 18,
      missionId: 18,
      agent: 'Dancer',
      dangerRate: 60,
      potential: 60,
      expectedCompletionDate: '2022-01-31T23:00:00.000Z',
    },
    {
      id: 19,
      missionId: 19,
      agent: 'White',
      dangerRate: 45,
      potential: 19,
      expectedCompletionDate: '2022-02-05T23:00:00.000Z',
    },
  ],
};
